defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: en-US
  - scope:
      path: en
    values:
      lang: en-US
  - scope:
      path: ja
    values:
      lang: ja-JP
  - scope:
      path: pt
    values:
      lang: pt-BR

encoding: utf-8

exclude:
  - README.md
  - .gitignore

plugins:
  - jekyll-optional-front-matter
